# pkgs/development/haskell-modules/configuration-hackage2nix.yaml

compiler: ghc-8.0.1

core-packages:
  - array-0.5.1.1
  - base-4.9.0.0
  - binary-0.8.3.0
  - bytestring-0.10.8.1
  - Cabal-1.24.0.0
  - containers-0.5.7.1
  - deepseq-1.4.2.0
  - directory-1.2.6.2
  - filepath-1.4.1.0
  - ghc-8.0.1
  - ghc-boot-8.0.1
  - ghc-boot-th-8.0.1
  - ghc-prim-0.5.0.0
  - ghci-8.0.1
  - haskeline-0.7.2.3
  - hoopl-3.10.2.1
  - hpc-0.6.0.3
  - integer-gmp-1.0.0.1
  - pretty-1.1.3.3
  - process-1.4.2.0
  - rts-1.0
  - template-haskell-2.11.0.0
  - terminfo-0.4.0.2
  - time-1.6.0.1
  - transformers-0.5.2.0
  - unix-2.7.2.0
  - xhtml-3000.2.1

default-package-overrides:
  # Add overrides in this section only for packages that are *not* part of
  # Stackage to make sure we're conforming to their preferred version list.

extra-packages:
  - aeson < 0.8                         # newer versions don't work with GHC 6.12.3
  - binary > 0.7 && < 0.8               # binary 0.8.x is the latest, but it's largely unsupported so far
  - Cabal == 1.18.*                     # required for cabal-install et al on old GHC versions
  - Cabal == 1.20.*                     # required for cabal-install et al on old GHC versions
  - containers < 0.5                    # required to build alex with GHC 6.12.3
  - control-monad-free < 0.6            # newer versions don't compile with anything but GHC 7.8.x
  - deepseq == 1.3.0.1                  # required to build Cabal with GHC 6.12.3
  - descriptive < 0.1                   # required for structured-haskell-mode-1.0.8
  - gloss < 1.9.3                       # new versions don't compile with GHC 7.8.x
  - haddock-api < 2.16                  # required on GHC 7.8.x
  - haskell-src-exts < 1.16             # required for structured-haskell-mode-1.0.8
  - mtl < 2.2                           # newer versions require transformers > 0.4.x, which we cannot provide in GHC 7.8.x
  - mtl-prelude < 2                     # required for to build postgrest on mtl 2.1.x platforms
  - parallel == 3.2.0.3                 # newer versions don't work with GHC 6.12.3
  - primitive == 0.5.1.*                # required to build alex with GHC 6.12.3
  - QuickCheck < 2                      # required by test-framework-quickcheck and its users
  - seqid < 0.2                         # newer versions depend on transformers 0.4.x which we cannot provide in GHC 7.8.x
  - seqid-streams < 0.2                 # newer versions depend on transformers 0.4.x which we cannot provide in GHC 7.8.x
  - split < 0.2                         # newer versions don't work with GHC 6.12.3
  - tar < 0.4.2.0                       # later versions don't work with GHC < 7.6.x
  - transformers == 0.4.3.*             # the latest version isn't supported by mtl yet
  - vector < 0.10.10                    # newer versions don't work with GHC 6.12.3
  - zlib < 0.6                          # newer versions break cabal-install

package-maintainers:
  peti:
    - cabal2nix
    - cabal-install
    - funcmp
    - git-annex
    - hackage-db
    - hledger-interest
    - hopenssl
    - hsdns
    - hsemail
    - hsyslog
    - jailbreak-cabal
    - language-nix
    - stack
    - streamproc
  gebner:
    - hledger-diff
  gridaphobe:
    - ghc-srcspan-plugin
    - located-base
  jb55:
    - skeletons
    - cased
    - pipes-csv
    - pipes-mongodb
  khumba:
    - goatee
    - goatee-gtk
  psibi:
    - path-pieces
    - persistent
    - persistent-mongoDB
    - persistent-mysql
    - persistent-postgresql
    - persistent-redis
    - persistent-sqlite
    - persistent-template
    - persistent-zookeeper
    - shakespeare
  abbradar:
    - Agda

dont-distribute-packages:
  # hard restrictions that really belong into meta.platforms
  AWin32Console:                                [ i686-linux, x86_64-linux, x86_64-darwin ]
  d3d11binding:                                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  DirectSound:                                  [ i686-linux, x86_64-linux, x86_64-darwin ]
  dx9base:                                      [ i686-linux, x86_64-linux, x86_64-darwin ]
  dx9d3d:                                       [ i686-linux, x86_64-linux, x86_64-darwin ]
  dx9d3dx:                                      [ i686-linux, x86_64-linux, x86_64-darwin ]
  hfsevents:                                    [ i686-linux, x86_64-linux ]
  hommage-ds:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  reactivity:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-dhcp-server:                            [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-errors:                                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-extras:                                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32:                                        [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-junction-point:                         [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-notify:                                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-security:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-services:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
  Win32-services-wrapper:                       [ i686-linux, x86_64-linux, x86_64-darwin ]
  XInput:                                       [ i686-linux, x86_64-linux, x86_64-darwin ]

  # Depens on shine, which is a ghcjs project.
  shine-varying:                                [ i686-linux, x86_64-linux, x86_64-darwin ]

  # these packages depend on software with an unfree license
  accelerate-cublas:                            [ i686-linux, x86_64-linux, x86_64-darwin ]
  accelerate-cuda:                              [ i686-linux, x86_64-linux, x86_64-darwin ]
  accelerate-cufft:                             [ i686-linux, x86_64-linux, x86_64-darwin ]
  accelerate-examples:                          [ i686-linux, x86_64-linux, x86_64-darwin ]
  accelerate-fft:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
  accelerate-fourier-benchmark:                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  bindings-yices:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
  ccelerate-cuda:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
  cublas:                                       [ i686-linux, x86_64-linux, x86_64-darwin ]
  cufft:                                        [ i686-linux, x86_64-linux, x86_64-darwin ]
  gloss-raster-accelerate:                      [ i686-linux, x86_64-linux, x86_64-darwin ]
  libnvvm:                                      [ i686-linux, x86_64-linux, x86_64-darwin ]
  Obsidian:                                     [ i686-linux, x86_64-linux, x86_64-darwin ]
  patch-image:                                  [ i686-linux, x86_64-linux, x86_64-darwin ]
  yices-easy:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  yices-painless:                               [ i686-linux, x86_64-linux, x86_64-darwin ]

  # soft restrictions because of build errors
  clang-pure:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  fltkhs-demos:                                 [ i686-linux, x86_64-linux, x86_64-darwin ]
  fltkhs-fluid-demos:                           [ i686-linux, x86_64-linux, x86_64-darwin ]
  fltkhs-hello-world:                           [ i686-linux, x86_64-linux, x86_64-darwin ]
  haste-gapi:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  haste-perch:                                  [ i686-linux, x86_64-linux, x86_64-darwin ]
  hplayground:                                  [ i686-linux, x86_64-linux, x86_64-darwin ]
  leksah:                                       [ i686-linux, x86_64-linux, x86_64-darwin ]
  sneathlane-haste:                             [ i686-linux, x86_64-linux, x86_64-darwin ]
  treersec:                                     [ i686-linux, x86_64-linux, x86_64-darwin ]
  yi-contrib:                                   [ i686-linux, x86_64-linux, x86_64-darwin ]
  temporal-csound:                              [ i686-linux, x86_64-linux, x86_64-darwin ]
  csound-catalog:                               [ i686-linux, x86_64-linux, x86_64-darwin ]
